## PANADAS 
- PANDAS IS A FAST, POWERFUL AND EASY TO USE OPEN SOURCE DATA ANALYSIS AND MANIPULATION LIBRARY
  
      - SERIES
      - DATAFRAME

In [4]:
import numpy as np
import pandas as pd

# SERIES

In [5]:
data = [10,20,30,40,50]
s1 = pd.Series(data)                        # Series is a class
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
type(s1)

pandas.core.series.Series

In [7]:
s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [8]:
list(s1.index)

[0, 1, 2, 3, 4]

In [9]:
s1.index = [101,102,103,104,105]
s1

101    10
102    20
103    30
104    40
105    50
dtype: int64

In [10]:
s1.index = ['a','b','c','d','e']
s1

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [11]:
s1.index = range(1005,1010)
s1

1005    10
1006    20
1007    30
1008    40
1009    50
dtype: int64

In [12]:
s1.index = ['a','b','c','d','e']
s1

a    10
b    20
c    30
d    40
e    50
dtype: int64

## ACCESSING DATA IN SERIES

In [13]:
s1[0]

C:\Users\sporj\AppData\Local\Temp\ipykernel_52420\643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

10

In [14]:
s1['a']

10

In [15]:
s1.iloc[3]                  # iloc is used for default index

40

In [16]:
s1.loc['d']                 # loc is used for default index

40

### ADD, UPDATE AND DELETE OPERATIONS

In [17]:
s1['f'] = 60             # add
s1

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [18]:
s1['c']=90             # update
s1

a    10
b    20
c    90
d    40
e    50
f    60
dtype: int64

In [19]:
s1.drop('d')        # this will show how it will look after deletion

a    10
b    20
c    90
e    50
f    60
dtype: int64

In [20]:
s1                # but in reality it is not deleted

a    10
b    20
c    90
d    40
e    50
f    60
dtype: int64

In [21]:
s2 = s1.drop('d')              # to delete we need to store it into other variable to see the chngs like we have done here
s2

a    10
b    20
c    90
e    50
f    60
dtype: int64

### SLICING

In [22]:
s1[:]

a    10
b    20
c    90
d    40
e    50
f    60
dtype: int64

In [23]:
s1[2:4]

c    90
d    40
dtype: int64

In [24]:
s1[::-1]

f    60
e    50
d    40
c    90
b    20
a    10
dtype: int64

### CREATING SERIES DATA FROM A DICTIONARY

In [25]:
data = {'jaipur'     : 'rajasthan', 
        'Mumbai'     : 'Maharashtra',
        'Kolkata'    : 'West bengal',
        'Chandigarh' : 'Punjab',
        'Lucknow'    : 'Uttar Pradesh'}

In [26]:
s2 = pd.Series(data)
s2

jaipur            rajasthan
Mumbai          Maharashtra
Kolkata         West bengal
Chandigarh           Punjab
Lucknow       Uttar Pradesh
dtype: object

In [27]:
s2.iloc[2]

'West bengal'

In [28]:
s2.loc['Kolkata']

'West bengal'

In [29]:
s2.index

Index(['jaipur', 'Mumbai', 'Kolkata', 'Chandigarh', 'Lucknow'], dtype='object')

In [30]:
s2.values

array(['rajasthan', 'Maharashtra', 'West bengal', 'Punjab',
       'Uttar Pradesh'], dtype=object)

In [31]:
s2.name = 'States and Capitals' 
s2

jaipur            rajasthan
Mumbai          Maharashtra
Kolkata         West bengal
Chandigarh           Punjab
Lucknow       Uttar Pradesh
Name: States and Capitals, dtype: object

In [32]:
s2.index.name = 'Capitals'

In [33]:
s2

Capitals
jaipur            rajasthan
Mumbai          Maharashtra
Kolkata         West bengal
Chandigarh           Punjab
Lucknow       Uttar Pradesh
Name: States and Capitals, dtype: object

In [34]:
s2.loc['jaipur']

'rajasthan'

In [35]:
s2.loc[['jaipur','Mumbai']]

Capitals
jaipur      rajasthan
Mumbai    Maharashtra
Name: States and Capitals, dtype: object

In [36]:
s3 = pd.Series(data=s2,index=['jaipur','Mumbai','Delhi','Bangluru','Lucknow'])
s3

jaipur          rajasthan
Mumbai        Maharashtra
Delhi                 NaN
Bangluru              NaN
Lucknow     Uttar Pradesh
Name: States and Capitals, dtype: object

### FUNCTIONS

In [37]:
s3.isnull()

jaipur      False
Mumbai      False
Delhi        True
Bangluru     True
Lucknow     False
Name: States and Capitals, dtype: bool

In [38]:
s3.isnull().sum()         # Using sum fun we are adding the value of null value

2

In [39]:
s3.notnull()              # Opp of isnull

jaipur       True
Mumbai       True
Delhi       False
Bangluru    False
Lucknow      True
Name: States and Capitals, dtype: bool

In [40]:
s3.notnull().sum()

3

In [41]:
s3['Chandigarh'] = 'Punjab'
s3['Kolkata'] = 'West Bengal'
s3['Patna'] = 'Bihar'
s3

jaipur            rajasthan
Mumbai          Maharashtra
Delhi                   NaN
Bangluru                NaN
Lucknow       Uttar Pradesh
Chandigarh           Punjab
Kolkata         West Bengal
Patna                 Bihar
Name: States and Capitals, dtype: object

In [42]:
s3.head()

jaipur          rajasthan
Mumbai        Maharashtra
Delhi                 NaN
Bangluru              NaN
Lucknow     Uttar Pradesh
Name: States and Capitals, dtype: object

In [43]:
s3.head(6)

jaipur            rajasthan
Mumbai          Maharashtra
Delhi                   NaN
Bangluru                NaN
Lucknow       Uttar Pradesh
Chandigarh           Punjab
Name: States and Capitals, dtype: object

In [44]:
s3.head(7)

jaipur            rajasthan
Mumbai          Maharashtra
Delhi                   NaN
Bangluru                NaN
Lucknow       Uttar Pradesh
Chandigarh           Punjab
Kolkata         West Bengal
Name: States and Capitals, dtype: object

In [45]:
s3.tail()

Bangluru                NaN
Lucknow       Uttar Pradesh
Chandigarh           Punjab
Kolkata         West Bengal
Patna                 Bihar
Name: States and Capitals, dtype: object

In [46]:
s3.tail(7)

Mumbai          Maharashtra
Delhi                   NaN
Bangluru                NaN
Lucknow       Uttar Pradesh
Chandigarh           Punjab
Kolkata         West Bengal
Patna                 Bihar
Name: States and Capitals, dtype: object

In [47]:
s3.tail(2)

Kolkata    West Bengal
Patna            Bihar
Name: States and Capitals, dtype: object

In [48]:
s3['abc'] = 'Punjab'             # here punjab is repeated but it is accepted but duplicate keys are not accepted
s3

jaipur            rajasthan
Mumbai          Maharashtra
Delhi                   NaN
Bangluru                NaN
Lucknow       Uttar Pradesh
Chandigarh           Punjab
Kolkata         West Bengal
Patna                 Bihar
abc                  Punjab
Name: States and Capitals, dtype: object

In [49]:
s3.duplicated()

jaipur        False
Mumbai        False
Delhi         False
Bangluru       True
Lucknow       False
Chandigarh    False
Kolkata       False
Patna         False
abc            True
Name: States and Capitals, dtype: bool

In [50]:
s3.duplicated().sum()

2

In [51]:
s3.drop_duplicates()                    #Duploicate va;ue will get deleted

jaipur            rajasthan
Mumbai          Maharashtra
Delhi                   NaN
Lucknow       Uttar Pradesh
Chandigarh           Punjab
Kolkata         West Bengal
Patna                 Bihar
Name: States and Capitals, dtype: object

In [52]:
s3

jaipur            rajasthan
Mumbai          Maharashtra
Delhi                   NaN
Bangluru                NaN
Lucknow       Uttar Pradesh
Chandigarh           Punjab
Kolkata         West Bengal
Patna                 Bihar
abc                  Punjab
Name: States and Capitals, dtype: object

In [53]:
s4 = s3.drop_duplicates()                  # Here the changes are permanant
s4

jaipur            rajasthan
Mumbai          Maharashtra
Delhi                   NaN
Lucknow       Uttar Pradesh
Chandigarh           Punjab
Kolkata         West Bengal
Patna                 Bihar
Name: States and Capitals, dtype: object

## DATAFRAMES

In [54]:
employee1 = pd.Series({'NAME' : 'ANKUR', 'GENDER' : 'MALE', 'SALARY' : 100000})
employee2 = pd.Series({'NAME' : 'ADITYA', 'GENDER' : 'MALE', 'SALARY' : 1500000})
employee3 = pd.Series({'NAME' : 'ARCHANA', 'GENDER' : 'FEMALE', 'SALARY' : 5300000})
employee4 = pd.Series({'NAME' : 'DEEPALI', 'GENDER' : 'FEMALE', 'SALARY' : 1300000})
employee5 = pd.Series({'NAME' : 'JAGJEET', 'GENDER' : 'MALE', 'SALARY' : 5600000})
employee6 = pd.Series({'NAME' : 'KEDAR', 'GENDER' : 'MALE', 'SALARY' : 3900000})
employee7 = pd.Series({'NAME' : 'MAHESH', 'GENDER' : 'MALE', 'SALARY' : 1350000})
employee8 = pd.Series({'NAME' : 'POOJA', 'GENDER' : 'FEMALE', 'SALARY' : 4520000})
employee9 = pd.Series({'NAME' : 'PRAPTI', 'GENDER' : 'FEMALE', 'SALARY' : 4530000})
employee10 = pd.Series({'NAME' : 'SHRUTIKA', 'GENDER' : 'FEMALE', 'SALARY' : 7850000})
employee11 = pd.Series({'NAME' : 'SIMRAN', 'GENDER' : 'FEMALE', 'SALARY' : 5980000})
employee12 = pd.Series({'NAME' : 'ASHUTOSH', 'GENDER' : 'MALE', 'SALARY' : 9800000})
employee13 = pd.Series({'NAME' : 'SURAJ', 'GENDER' : 'MALE', 'SALARY' : 8130000})
employee14 = pd.Series({'NAME' : 'SHWETA', 'GENDER' : 'FEMALE', 'SALARY' : 7260000})
employee15 = pd.Series({'NAME' : 'VEDIKA', 'GENDER' : 'FEMALE', 'SALARY' : 6360000})

In [55]:
employee = [employee1, employee2, employee3, employee4, employee5, employee6, employee7, employee8, employee9, employee10, employee11, employee12, employee13, employee14, employee15]
df = pd.DataFrame(data = employee, index = range(101,116))
df

         NAME  GENDER   SALARY
101     ANKUR    MALE   100000
102    ADITYA    MALE  1500000
103   ARCHANA  FEMALE  5300000
104   DEEPALI  FEMALE  1300000
105   JAGJEET    MALE  5600000
106     KEDAR    MALE  3900000
107    MAHESH    MALE  1350000
108     POOJA  FEMALE  4520000
109    PRAPTI  FEMALE  4530000
110  SHRUTIKA  FEMALE  7850000
111    SIMRAN  FEMALE  5980000
112  ASHUTOSH    MALE  9800000
113     SURAJ    MALE  8130000
114    SHWETA  FEMALE  7260000
115    VEDIKA  FEMALE  6360000

### IMPORTING CSV FILE

## THis is how we can import the file from the folder

df1 = pd.read_csv('drug200.csv')
df1

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 101 to 115
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NAME    15 non-null     object
 1   GENDER  15 non-null     object
 2   SALARY  15 non-null     int64
dtypes: int64(1), object(2)
memory usage: 492.0+ bytes

In [57]:
df.head()

        NAME  GENDER   SALARY
101    ANKUR    MALE   100000
102   ADITYA    MALE  1500000
103  ARCHANA  FEMALE  5300000
104  DEEPALI  FEMALE  1300000
105  JAGJEET    MALE  5600000

In [58]:
df.tail()

         NAME  GENDER   SALARY
111    SIMRAN  FEMALE  5980000
112  ASHUTOSH    MALE  9800000
113     SURAJ    MALE  8130000
114    SHWETA  FEMALE  7260000
115    VEDIKA  FEMALE  6360000

In [59]:
df.name = 'Employee Details'
df.index.name = 'Employee ID'

In [60]:
df

                 NAME  GENDER   SALARY
Employee ID
101             ANKUR    MALE   100000
102            ADITYA    MALE  1500000
103           ARCHANA  FEMALE  5300000
104           DEEPALI  FEMALE  1300000
105           JAGJEET    MALE  5600000
106             KEDAR    MALE  3900000
107            MAHESH    MALE  1350000
108             POOJA  FEMALE  4520000
109            PRAPTI  FEMALE  4530000
110          SHRUTIKA  FEMALE  7850000
111            SIMRAN  FEMALE  5980000
112          ASHUTOSH    MALE  9800000
113             SURAJ    MALE  8130000
114            SHWETA  FEMALE  7260000
115            VEDIKA  FEMALE  6360000

In [61]:
df.name

'Employee Details'

In [62]:
df.columns

Index(['NAME', 'GENDER', 'SALARY'], dtype='object')

## ACCESSING DATA FROM DATAFRAME

In [63]:
df

                 NAME  GENDER   SALARY
Employee ID
101             ANKUR    MALE   100000
102            ADITYA    MALE  1500000
103           ARCHANA  FEMALE  5300000
104           DEEPALI  FEMALE  1300000
105           JAGJEET    MALE  5600000
106             KEDAR    MALE  3900000
107            MAHESH    MALE  1350000
108             POOJA  FEMALE  4520000
109            PRAPTI  FEMALE  4530000
110          SHRUTIKA  FEMALE  7850000
111            SIMRAN  FEMALE  5980000
112          ASHUTOSH    MALE  9800000
113             SURAJ    MALE  8130000
114            SHWETA  FEMALE  7260000
115            VEDIKA  FEMALE  6360000

In [64]:
df['NAME']               # it is in the data series format

Employee ID
101       ANKUR
102      ADITYA
103     ARCHANA
104     DEEPALI
105     JAGJEET
106       KEDAR
107      MAHESH
108       POOJA
109      PRAPTI
110    SHRUTIKA
111      SIMRAN
112    ASHUTOSH
113       SURAJ
114      SHWETA
115      VEDIKA
Name: NAME, dtype: object

In [65]:
df['SALARY']                   # it is in the data series format

Employee ID
101     100000
102    1500000
103    5300000
104    1300000
105    5600000
106    3900000
107    1350000
108    4520000
109    4530000
110    7850000
111    5980000
112    9800000
113    8130000
114    7260000
115    6360000
Name: SALARY, dtype: int64

In [66]:
df[['NAME']]                       # it is in the data dataframe format

                 NAME
Employee ID
101             ANKUR
102            ADITYA
103           ARCHANA
104           DEEPALI
105           JAGJEET
106             KEDAR
107            MAHESH
108             POOJA
109            PRAPTI
110          SHRUTIKA
111            SIMRAN
112          ASHUTOSH
113             SURAJ
114            SHWETA
115            VEDIKA

In [67]:
df[['SALARY']]                          # it is in the data dataframe format

              SALARY
Employee ID
101           100000
102          1500000
103          5300000
104          1300000
105          5600000
106          3900000
107          1350000
108          4520000
109          4530000
110          7850000
111          5980000
112          9800000
113          8130000
114          7260000
115          6360000

In [68]:
df[['NAME','SALARY']]                         # HERE THERE ARE 2 CLMS THEN WE CANT GIVE SINGLE BRACKET WE HAVE TO USE 2 BRACKETS BCOZ OF THERE ARE TWO COLUMNS THEN IT IS THE DATAFRAME NOT DATASERIES

                 NAME   SALARY
Employee ID
101             ANKUR   100000
102            ADITYA  1500000
103           ARCHANA  5300000
104           DEEPALI  1300000
105           JAGJEET  5600000
106             KEDAR  3900000
107            MAHESH  1350000
108             POOJA  4520000
109            PRAPTI  4530000
110          SHRUTIKA  7850000
111            SIMRAN  5980000
112          ASHUTOSH  9800000
113             SURAJ  8130000
114            SHWETA  7260000
115            VEDIKA  6360000

In [69]:
df[['NAME','GENDER','SALARY']]

                 NAME  GENDER   SALARY
Employee ID
101             ANKUR    MALE   100000
102            ADITYA    MALE  1500000
103           ARCHANA  FEMALE  5300000
104           DEEPALI  FEMALE  1300000
105           JAGJEET    MALE  5600000
106             KEDAR    MALE  3900000
107            MAHESH    MALE  1350000
108             POOJA  FEMALE  4520000
109            PRAPTI  FEMALE  4530000
110          SHRUTIKA  FEMALE  7850000
111            SIMRAN  FEMALE  5980000
112          ASHUTOSH    MALE  9800000
113             SURAJ    MALE  8130000
114            SHWETA  FEMALE  7260000
115            VEDIKA  FEMALE  6360000

In [70]:
cols = ['NAME','SALARY']                # 2 meth of above
df[cols]

                 NAME   SALARY
Employee ID
101             ANKUR   100000
102            ADITYA  1500000
103           ARCHANA  5300000
104           DEEPALI  1300000
105           JAGJEET  5600000
106             KEDAR  3900000
107            MAHESH  1350000
108             POOJA  4520000
109            PRAPTI  4530000
110          SHRUTIKA  7850000
111            SIMRAN  5980000
112          ASHUTOSH  9800000
113             SURAJ  8130000
114            SHWETA  7260000
115            VEDIKA  6360000

In [71]:
df.NAME

Employee ID
101       ANKUR
102      ADITYA
103     ARCHANA
104     DEEPALI
105     JAGJEET
106       KEDAR
107      MAHESH
108       POOJA
109      PRAPTI
110    SHRUTIKA
111      SIMRAN
112    ASHUTOSH
113       SURAJ
114      SHWETA
115      VEDIKA
Name: NAME, dtype: object

In [72]:
df.loc[104]

NAME      DEEPALI
GENDER     FEMALE
SALARY    1300000
Name: 104, dtype: object

In [73]:
df.loc[[104]]

                NAME  GENDER   SALARY
Employee ID
104          DEEPALI  FEMALE  1300000

In [74]:
df.loc[[111]]

               NAME  GENDER   SALARY
Employee ID
111          SIMRAN  FEMALE  5980000

In [75]:
df.iloc[[3]]               # iloc = default index

                NAME  GENDER   SALARY
Employee ID
104          DEEPALI  FEMALE  1300000

In [76]:
df.iloc[[6]]

               NAME GENDER   SALARY
Employee ID
107          MAHESH   MALE  1350000

In [77]:
df.loc[[107]]

               NAME GENDER   SALARY
Employee ID
107          MAHESH   MALE  1350000

In [78]:
df.loc[[101,105]]

                NAME GENDER   SALARY
Employee ID
101            ANKUR   MALE   100000
105          JAGJEET   MALE  5600000

In [79]:
df.loc[[102,105,106,107,115]]

                NAME  GENDER   SALARY
Employee ID
102           ADITYA    MALE  1500000
105          JAGJEET    MALE  5600000
106            KEDAR    MALE  3900000
107           MAHESH    MALE  1350000
115           VEDIKA  FEMALE  6360000

In [80]:
df.iloc[[0,4,5,6,7,14]]

                NAME  GENDER   SALARY
Employee ID
101            ANKUR    MALE   100000
105          JAGJEET    MALE  5600000
106            KEDAR    MALE  3900000
107           MAHESH    MALE  1350000
108            POOJA  FEMALE  4520000
115           VEDIKA  FEMALE  6360000

### ACCESSING SPECIFIC VALUES

In [81]:
df.SALARY

Employee ID
101     100000
102    1500000
103    5300000
104    1300000
105    5600000
106    3900000
107    1350000
108    4520000
109    4530000
110    7850000
111    5980000
112    9800000
113    8130000
114    7260000
115    6360000
Name: SALARY, dtype: int64

In [82]:
df.SALARY[109]

4530000

In [83]:
df['SALARY'][109]

4530000

In [85]:
df[109]['SALARY']

KeyError: 109

In [86]:
df.loc[109]['SALARY']

4530000

In [87]:
df.loc[109,'SALARY']

4530000

In [88]:
df.iloc[8]['SALARY']             # CANT GIVE QUAMA SEPARATED VALUE LIKE ABOVE IN ILOC

4530000

In [89]:
df['SALARY'][8]

KeyError: 8

In [92]:
df['SALARY',8]

KeyError: ('SALARY', 8)

In [93]:
df.loc[108,'NAME']

'POOJA'

In [94]:
df.iloc[7]['NAME']

'POOJA'

In [95]:
df.loc[[102,103,104,105,]]['SALARY']

Employee ID
102    1500000
103    5300000
104    1300000
105    5600000
Name: SALARY, dtype: int64

In [96]:
df.loc[[102,103,104,105,]][['NAME','SALARY']]

                NAME   SALARY
Employee ID
102           ADITYA  1500000
103          ARCHANA  5300000
104          DEEPALI  1300000
105          JAGJEET  5600000

In [97]:
df.loc[[102,103,104,105],['NAME','SALARY']]

                NAME   SALARY
Employee ID
102           ADITYA  1500000
103          ARCHANA  5300000
104          DEEPALI  1300000
105          JAGJEET  5600000

In [98]:
df.loc[102::2]

                 NAME  GENDER   SALARY
Employee ID
102            ADITYA    MALE  1500000
104           DEEPALI  FEMALE  1300000
106             KEDAR    MALE  3900000
108             POOJA  FEMALE  4520000
110          SHRUTIKA  FEMALE  7850000
112          ASHUTOSH    MALE  9800000
114            SHWETA  FEMALE  7260000

In [99]:
df.loc[102::2][['SALARY']]

              SALARY
Employee ID
102          1500000
104          1300000
106          3900000
108          4520000
110          7850000
112          9800000
114          7260000

In [100]:
df.iloc[1:15:2]

                 NAME  GENDER   SALARY
Employee ID
102            ADITYA    MALE  1500000
104           DEEPALI  FEMALE  1300000
106             KEDAR    MALE  3900000
108             POOJA  FEMALE  4520000
110          SHRUTIKA  FEMALE  7850000
112          ASHUTOSH    MALE  9800000
114            SHWETA  FEMALE  7260000

### ADDING AND DELETING ROWS AND COLUMNS

In [101]:
df

                 NAME  GENDER   SALARY
Employee ID
101             ANKUR    MALE   100000
102            ADITYA    MALE  1500000
103           ARCHANA  FEMALE  5300000
104           DEEPALI  FEMALE  1300000
105           JAGJEET    MALE  5600000
106             KEDAR    MALE  3900000
107            MAHESH    MALE  1350000
108             POOJA  FEMALE  4520000
109            PRAPTI  FEMALE  4530000
110          SHRUTIKA  FEMALE  7850000
111            SIMRAN  FEMALE  5980000
112          ASHUTOSH    MALE  9800000
113             SURAJ    MALE  8130000
114            SHWETA  FEMALE  7260000
115            VEDIKA  FEMALE  6360000

In [102]:
df.loc[116] = ['VIVEK', 'MALE', 1560000]              # this is how ne value to the row we can add new value
df

                 NAME  GENDER   SALARY
Employee ID
101             ANKUR    MALE   100000
102            ADITYA    MALE  1500000
103           ARCHANA  FEMALE  5300000
104           DEEPALI  FEMALE  1300000
105           JAGJEET    MALE  5600000
106             KEDAR    MALE  3900000
107            MAHESH    MALE  1350000
108             POOJA  FEMALE  4520000
109            PRAPTI  FEMALE  4530000
110          SHRUTIKA  FEMALE  7850000
111            SIMRAN  FEMALE  5980000
112          ASHUTOSH    MALE  9800000
113             SURAJ    MALE  8130000
114            SHWETA  FEMALE  7260000
115            VEDIKA  FEMALE  6360000
116             VIVEK    MALE  1560000

In [103]:
df['AGE'] = np.random.randint(25,50,16)                     # This is how column can be added
df

                 NAME  GENDER   SALARY  AGE
Employee ID
101             ANKUR    MALE   100000   39
102            ADITYA    MALE  1500000   28
103           ARCHANA  FEMALE  5300000   40
104           DEEPALI  FEMALE  1300000   30
105           JAGJEET    MALE  5600000   44
106             KEDAR    MALE  3900000   39
107            MAHESH    MALE  1350000   43
108             POOJA  FEMALE  4520000   32
109            PRAPTI  FEMALE  4530000   39
110          SHRUTIKA  FEMALE  7850000   42
111            SIMRAN  FEMALE  5980000   34
112          ASHUTOSH    MALE  9800000   36
113             SURAJ    MALE  8130000   47
114            SHWETA  FEMALE  7260000   47
115            VEDIKA  FEMALE  6360000   44
116             VIVEK    MALE  1560000   45

In [104]:
df['CITY'] = 'PUNE'
df

                 NAME  GENDER   SALARY  AGE  CITY
Employee ID
101             ANKUR    MALE   100000   39  PUNE
102            ADITYA    MALE  1500000   28  PUNE
103           ARCHANA  FEMALE  5300000   40  PUNE
104           DEEPALI  FEMALE  1300000   30  PUNE
105           JAGJEET    MALE  5600000   44  PUNE
106             KEDAR    MALE  3900000   39  PUNE
107            MAHESH    MALE  1350000   43  PUNE
108             POOJA  FEMALE  4520000   32  PUNE
109            PRAPTI  FEMALE  4530000   39  PUNE
110          SHRUTIKA  FEMALE  7850000   42  PUNE
111            SIMRAN  FEMALE  5980000   34  PUNE
112          ASHUTOSH    MALE  9800000   36  PUNE
113             SURAJ    MALE  8130000   47  PUNE
114            SHWETA  FEMALE  7260000   47  PUNE
115            VEDIKA  FEMALE  6360000   44  PUNE
116             VIVEK    MALE  1560000   45  PUNE

In [105]:
df.drop('CITY', axis = 1, inplace = True)             # Axis 1 for column wise

In [106]:
df

                 NAME  GENDER   SALARY  AGE
Employee ID
101             ANKUR    MALE   100000   39
102            ADITYA    MALE  1500000   28
103           ARCHANA  FEMALE  5300000   40
104           DEEPALI  FEMALE  1300000   30
105           JAGJEET    MALE  5600000   44
106             KEDAR    MALE  3900000   39
107            MAHESH    MALE  1350000   43
108             POOJA  FEMALE  4520000   32
109            PRAPTI  FEMALE  4530000   39
110          SHRUTIKA  FEMALE  7850000   42
111            SIMRAN  FEMALE  5980000   34
112          ASHUTOSH    MALE  9800000   36
113             SURAJ    MALE  8130000   47
114            SHWETA  FEMALE  7260000   47
115            VEDIKA  FEMALE  6360000   44
116             VIVEK    MALE  1560000   45

In [107]:
df.drop(116, axis = 0, inplace = True)                  # Axis 0 for rowwise

In [108]:
df

                 NAME  GENDER   SALARY  AGE
Employee ID
101             ANKUR    MALE   100000   39
102            ADITYA    MALE  1500000   28
103           ARCHANA  FEMALE  5300000   40
104           DEEPALI  FEMALE  1300000   30
105           JAGJEET    MALE  5600000   44
106             KEDAR    MALE  3900000   39
107            MAHESH    MALE  1350000   43
108             POOJA  FEMALE  4520000   32
109            PRAPTI  FEMALE  4530000   39
110          SHRUTIKA  FEMALE  7850000   42
111            SIMRAN  FEMALE  5980000   34
112          ASHUTOSH    MALE  9800000   36
113             SURAJ    MALE  8130000   47
114            SHWETA  FEMALE  7260000   47
115            VEDIKA  FEMALE  6360000   44

In [109]:
n = input('Enter the name of the employee : ')
g = input('Enter the gender of the employee : ')
s = int(input('Enter the salary of the employee : '))
a = int(input('Enter the age of the employee : '))

df.loc[116] = [n,g,s,a]
df

Enter the name of the employee :  HARISH
Enter the gender of the employee :  MALE
Enter the salary of the employee :  45610000
Enter the age of the employee :  42

                 NAME  GENDER    SALARY  AGE
Employee ID
101             ANKUR    MALE    100000   39
102            ADITYA    MALE   1500000   28
103           ARCHANA  FEMALE   5300000   40
104           DEEPALI  FEMALE   1300000   30
105           JAGJEET    MALE   5600000   44
106             KEDAR    MALE   3900000   39
107            MAHESH    MALE   1350000   43
108             POOJA  FEMALE   4520000   32
109            PRAPTI  FEMALE   4530000   39
110          SHRUTIKA  FEMALE   7850000   42
111            SIMRAN  FEMALE   5980000   34
112          ASHUTOSH    MALE   9800000   36
113             SURAJ    MALE   8130000   47
114            SHWETA  FEMALE   7260000   47
115            VEDIKA  FEMALE   6360000   44
116            HARISH    MALE  45610000   42

In [111]:
df[df.AGE>40]

                 NAME  GENDER    SALARY  AGE
Employee ID
105           JAGJEET    MALE   5600000   44
107            MAHESH    MALE   1350000   43
110          SHRUTIKA  FEMALE   7850000   42
113             SURAJ    MALE   8130000   47
114            SHWETA  FEMALE   7260000   47
115            VEDIKA  FEMALE   6360000   44
116            HARISH    MALE  45610000   42

In [112]:
df[df.AGE>40][['NAME','SALARY']]

                 NAME    SALARY
Employee ID
105           JAGJEET   5600000
107            MAHESH   1350000
110          SHRUTIKA   7850000
113             SURAJ   8130000
114            SHWETA   7260000
115            VEDIKA   6360000
116            HARISH  45610000

In [113]:
df[df.NAME == 'ANKUR']

              NAME GENDER  SALARY  AGE
Employee ID
101          ANKUR   MALE  100000   39

In [114]:
df[df.GENDER == 'FEMALE']

                 NAME  GENDER   SALARY  AGE
Employee ID
103           ARCHANA  FEMALE  5300000   40
104           DEEPALI  FEMALE  1300000   30
108             POOJA  FEMALE  4520000   32
109            PRAPTI  FEMALE  4530000   39
110          SHRUTIKA  FEMALE  7850000   42
111            SIMRAN  FEMALE  5980000   34
114            SHWETA  FEMALE  7260000   47
115            VEDIKA  FEMALE  6360000   44

In [130]:
df[df.GENDER == 'MALE'][df.SALARY > 11000000]

C:\Users\sporj\AppData\Local\Temp\ipykernel_52420\3945920359.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.GENDER == 'MALE'][df.SALARY > 11000000]

               NAME GENDER    SALARY  AGE
Employee ID
116          HARISH   MALE  45610000   42

In [134]:
df[df.GENDER == 'MALE'][df.SALARY > 4500000] [df.AGE > 42]

C:\Users\sporj\AppData\Local\Temp\ipykernel_52420\1037852601.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.GENDER == 'MALE'][df.SALARY > 4500000] [df.AGE > 42]
C:\Users\sporj\AppData\Local\Temp\ipykernel_52420\1037852601.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.GENDER == 'MALE'][df.SALARY > 4500000] [df.AGE > 42]

                NAME GENDER   SALARY  AGE
Employee ID
105          JAGJEET   MALE  5600000   44
113            SURAJ   MALE  8130000   47

### IMPORTANT FUNCTIONS

In [135]:
df

                 NAME  GENDER    SALARY  AGE
Employee ID
101             ANKUR    MALE    100000   39
102            ADITYA    MALE   1500000   28
103           ARCHANA  FEMALE   5300000   40
104           DEEPALI  FEMALE   1300000   30
105           JAGJEET    MALE   5600000   44
106             KEDAR    MALE   3900000   39
107            MAHESH    MALE   1350000   43
108             POOJA  FEMALE   4520000   32
109            PRAPTI  FEMALE   4530000   39
110          SHRUTIKA  FEMALE   7850000   42
111            SIMRAN  FEMALE   5980000   34
112          ASHUTOSH    MALE   9800000   36
113             SURAJ    MALE   8130000   47
114            SHWETA  FEMALE   7260000   47
115            VEDIKA  FEMALE   6360000   44
116            HARISH    MALE  45610000   42

In [142]:
df.loc[117] = df.loc[106]
df.loc[118] = df.loc[108]

df.loc[119] = ['ANKUSH', 'MALE', np.nan, 32]
df.loc[120] = ['KRISHNA', 'MALE', np.nan, 22]
df

                 NAME  GENDER      SALARY  AGE
Employee ID
101             ANKUR    MALE    100000.0   39
102            ADITYA    MALE   1500000.0   28
103           ARCHANA  FEMALE   5300000.0   40
104           DEEPALI  FEMALE   1300000.0   30
105           JAGJEET    MALE   5600000.0   44
106             KEDAR    MALE   3900000.0   39
107            MAHESH    MALE   1350000.0   43
108             POOJA  FEMALE   4520000.0   32
109            PRAPTI  FEMALE   4530000.0   39
110          SHRUTIKA  FEMALE   7850000.0   42
111            SIMRAN  FEMALE   5980000.0   34
112          ASHUTOSH    MALE   9800000.0   36
113             SURAJ    MALE   8130000.0   47
114            SHWETA  FEMALE   7260000.0   47
115            VEDIKA  FEMALE   6360000.0   44
116            HARISH    MALE  45610000.0   42
117             KEDAR    MALE   3900000.0   39
118             POOJA  FEMALE   4520000.0   32
119            ANKUSH    MALE         NaN   32
120           KRISHNA    MALE         NaN   22

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 101 to 120
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NAME    20 non-null     object
 1   GENDER  20 non-null     object
 2   SALARY  18 non-null     float64
 3   AGE     20 non-null     int64
dtypes: float64(1), int64(1), object(2)
memory usage: 800.0+ bytes

In [144]:
df.head()

                NAME  GENDER     SALARY  AGE
Employee ID
101            ANKUR    MALE   100000.0   39
102           ADITYA    MALE  1500000.0   28
103          ARCHANA  FEMALE  5300000.0   40
104          DEEPALI  FEMALE  1300000.0   30
105          JAGJEET    MALE  5600000.0   44

In [145]:
df.tail()

                NAME  GENDER      SALARY  AGE
Employee ID
116           HARISH    MALE  45610000.0   42
117            KEDAR    MALE   3900000.0   39
118            POOJA  FEMALE   4520000.0   32
119           ANKUSH    MALE         NaN   32
120          KRISHNA    MALE         NaN   22

In [146]:
df.isnull().sum()

NAME      0
GENDER    0
SALARY    2
AGE       0
dtype: int64

In [147]:
df.notnull().sum()

NAME      20
GENDER    20
SALARY    18
AGE       20
dtype: int64

In [148]:
df.duplicated().sum()

2

In [149]:
df.nunique()

NAME      18
GENDER     2
SALARY    16
AGE       12
dtype: int64

In [151]:
df.NAME.unique()

array(['ANKUR', 'ADITYA', 'ARCHANA', 'DEEPALI', 'JAGJEET', 'KEDAR',
       'MAHESH', 'POOJA', 'PRAPTI', 'SHRUTIKA', 'SIMRAN', 'ASHUTOSH',
       'SURAJ', 'SHWETA', 'VEDIKA', 'HARISH', 'ANKUSH', 'KRISHNA'],
      dtype=object)

In [155]:
df['NAME'].unique()

array(['ANKUR', 'ADITYA', 'ARCHANA', 'DEEPALI', 'JAGJEET', 'KEDAR',
       'MAHESH', 'POOJA', 'PRAPTI', 'SHRUTIKA', 'SIMRAN', 'ASHUTOSH',
       'SURAJ', 'SHWETA', 'VEDIKA', 'HARISH', 'ANKUSH', 'KRISHNA'],
      dtype=object)

In [156]:
df.AGE.unique()

array([39, 28, 40, 30, 44, 43, 32, 42, 34, 36, 47, 22], dtype=int64)

In [157]:
df.sort_values(by = 'NAME')

                 NAME  GENDER      SALARY  AGE
Employee ID
102            ADITYA    MALE   1500000.0   28
101             ANKUR    MALE    100000.0   39
119            ANKUSH    MALE         NaN   32
103           ARCHANA  FEMALE   5300000.0   40
112          ASHUTOSH    MALE   9800000.0   36
104           DEEPALI  FEMALE   1300000.0   30
116            HARISH    MALE  45610000.0   42
105           JAGJEET    MALE   5600000.0   44
106             KEDAR    MALE   3900000.0   39
117             KEDAR    MALE   3900000.0   39
120           KRISHNA    MALE         NaN   22
107            MAHESH    MALE   1350000.0   43
108             POOJA  FEMALE   4520000.0   32
118             POOJA  FEMALE   4520000.0   32
109            PRAPTI  FEMALE   4530000.0   39
110          SHRUTIKA  FEMALE   7850000.0   42
114            SHWETA  FEMALE   7260000.0   47
111            SIMRAN  FEMALE   5980000.0   34
113             SURAJ    MALE   8130000.0   47
115            VEDIKA  FEMALE   6360000.0   44

In [161]:
df.sort_values(by = 'NAME', ascending = False)

                 NAME  GENDER      SALARY  AGE
Employee ID
115            VEDIKA  FEMALE   6360000.0   44
113             SURAJ    MALE   8130000.0   47
111            SIMRAN  FEMALE   5980000.0   34
114            SHWETA  FEMALE   7260000.0   47
110          SHRUTIKA  FEMALE   7850000.0   42
109            PRAPTI  FEMALE   4530000.0   39
118             POOJA  FEMALE   4520000.0   32
108             POOJA  FEMALE   4520000.0   32
107            MAHESH    MALE   1350000.0   43
120           KRISHNA    MALE         NaN   22
106             KEDAR    MALE   3900000.0   39
117             KEDAR    MALE   3900000.0   39
105           JAGJEET    MALE   5600000.0   44
116            HARISH    MALE  45610000.0   42
104           DEEPALI  FEMALE   1300000.0   30
112          ASHUTOSH    MALE   9800000.0   36
103           ARCHANA  FEMALE   5300000.0   40
119            ANKUSH    MALE         NaN   32
101             ANKUR    MALE    100000.0   39
102            ADITYA    MALE   1500000.0   28

In [162]:
pd.concat([df,df], axis = 1)                    ## Same data will be concatenated rowwise

,NAME,GENDER,SALARY,AGE,NAME,GENDER,SALARY,AGE
Employee ID,,,,,,,,
101,ANKUR,MALE,100000.0,39,ANKUR,MALE,100000.0,39
102,ADITYA,MALE,1500000.0,28,ADITYA,MALE,1500000.0,28
103,ARCHANA,FEMALE,5300000.0,40,ARCHANA,FEMALE,5300000.0,40
104,DEEPALI,FEMALE,1300000.0,30,DEEPALI,FEMALE,1300000.0,30
105,JAGJEET,MALE,5600000.0,44,JAGJEET,MALE,5600000.0,44
106,KEDAR,MALE,3900000.0,39,KEDAR,MALE,3900000.0,39
107,MAHESH,MALE,1350000.0,43,MAHESH,MALE,1350000.0,43
108,POOJA,FEMALE,4520000.0,32,POOJA,FEMALE,4520000.0,32
109,PRAPTI,FEMALE,4530000.0,39,PRAPTI,FEMALE,4530000.0,39
110,SHRUTIKA,FEMALE,7850000.0,42,SHRUTIKA,FEMALE,7850000.0,42
111,SIMRAN,FEMALE,5980000.0,34,SIMRAN,FEMALE,5980000.0,34
112,ASHUTOSH,MALE,9800000.0,36,ASHUTOSH,MALE,9800000.0,36
113,SURAJ,MALE,8130000.0,47,SURAJ,MALE,8130000.0,47
114,SHWETA,FEMALE,7260000.0,47,SHWETA,FEMALE,7260000.0,47
115,VEDIKA,FEMALE,6360000.0,44,VEDIKA,FEMALE,6360000.0,44
116,HARISH,MALE,45610000.0,42,HARISH,MALE,45610000.0,42
117,KEDAR,MALE,3900000.0,39,KEDAR,MALE,3900000.0,39
118,POOJA,FEMALE,4520000.0,32,POOJA,FEMALE,4520000.0,32
119,ANKUSH,MALE,NaN,32,ANKUSH,MALE,NaN,32
120,KRISHNA,MALE,NaN,22,KRISHNA,MALE,NaN,22

In [163]:
pd.concat([df,df], axis = 0)                               ## Same data will be concatenated rowwise

                 NAME  GENDER      SALARY  AGE
Employee ID
101             ANKUR    MALE    100000.0   39
102            ADITYA    MALE   1500000.0   28
103           ARCHANA  FEMALE   5300000.0   40
104           DEEPALI  FEMALE   1300000.0   30
105           JAGJEET    MALE   5600000.0   44
106             KEDAR    MALE   3900000.0   39
107            MAHESH    MALE   1350000.0   43
108             POOJA  FEMALE   4520000.0   32
109            PRAPTI  FEMALE   4530000.0   39
110          SHRUTIKA  FEMALE   7850000.0   42
111            SIMRAN  FEMALE   5980000.0   34
112          ASHUTOSH    MALE   9800000.0   36
113             SURAJ    MALE   8130000.0   47
114            SHWETA  FEMALE   7260000.0   47
115            VEDIKA  FEMALE   6360000.0   44
116            HARISH    MALE  45610000.0   42
117             KEDAR    MALE   3900000.0   39
118             POOJA  FEMALE   4520000.0   32
119            ANKUSH    MALE         NaN   32
120           KRISHNA    MALE         NaN   22
101             ANKUR    MALE    100000.0   39
102            ADITYA    MALE   1500000.0   28
103           ARCHANA  FEMALE   5300000.0   40
104           DEEPALI  FEMALE   1300000.0   30
105           JAGJEET    MALE   5600000.0   44
106             KEDAR    MALE   3900000.0   39
107            MAHESH    MALE   1350000.0   43
108             POOJA  FEMALE   4520000.0   32
109            PRAPTI  FEMALE   4530000.0   39
110          SHRUTIKA  FEMALE   7850000.0   42
111            SIMRAN  FEMALE   5980000.0   34
112          ASHUTOSH    MALE   9800000.0   36
113             SURAJ    MALE   8130000.0   47
114            SHWETA  FEMALE   7260000.0   47
115            VEDIKA  FEMALE   6360000.0   44
116            HARISH    MALE  45610000.0   42
117             KEDAR    MALE   3900000.0   39
118             POOJA  FEMALE   4520000.0   32
119            ANKUSH    MALE         NaN   32
120           KRISHNA    MALE         NaN   22

In [164]:
df.value_counts()

NAME      GENDER  SALARY      AGE
KEDAR     MALE    3900000.0   39     2
POOJA     FEMALE  4520000.0   32     2
ADITYA    MALE    1500000.0   28     1
ANKUR     MALE    100000.0    39     1
ARCHANA   FEMALE  5300000.0   40     1
ASHUTOSH  MALE    9800000.0   36     1
DEEPALI   FEMALE  1300000.0   30     1
HARISH    MALE    45610000.0  42     1
JAGJEET   MALE    5600000.0   44     1
MAHESH    MALE    1350000.0   43     1
PRAPTI    FEMALE  4530000.0   39     1
SHRUTIKA  FEMALE  7850000.0   42     1
SHWETA    FEMALE  7260000.0   47     1
SIMRAN    FEMALE  5980000.0   34     1
SURAJ     MALE    8130000.0   47     1
VEDIKA    FEMALE  6360000.0   44     1
Name: count, dtype: int64

In [165]:
df.GENDER.value_counts()

GENDER
MALE      11
FEMALE     9
Name: count, dtype: int64

In [166]:
df.count()

NAME      20
GENDER    20
SALARY    18
AGE       20
dtype: int64

In [167]:
df.describe()

             SALARY        AGE
count  1.800000e+01  20.000000
mean   7.083889e+06  37.550000
std    9.960825e+06   6.660765
min    1.000000e+05  22.000000
25%    3.900000e+06  32.000000
50%    4.915000e+06  39.000000
75%    7.035000e+06  42.250000
max    4.561000e+07  47.000000

In [168]:
df.AGE.mean()

37.55

In [169]:
df.SALARY.mean()

7083888.888888889

In [173]:
df.groupby(by = 'GENDER')['SALARY'].mean()

GENDER
FEMALE    5.291111e+06
MALE      8.876667e+06
Name: SALARY, dtype: float64

In [174]:
df['CITY'] = ['PUNE', 'DELHI', 'MUMBAI', 'NAGPUR', 'PUNE', 'DELHI', 'MUMBAI', 'NAGPUR', 'PUNE', 'DELHI', 'MUMBAI', 'NAGPUR', 'PUNE', 'DELHI', 'MUMBAI', 'NAGPUR', 'PUNE', 'DELHI', 'MUMBAI', 'NAGPUR']
df

                 NAME  GENDER      SALARY  AGE    CITY
Employee ID
101             ANKUR    MALE    100000.0   39    PUNE
102            ADITYA    MALE   1500000.0   28   DELHI
103           ARCHANA  FEMALE   5300000.0   40  MUMBAI
104           DEEPALI  FEMALE   1300000.0   30  NAGPUR
105           JAGJEET    MALE   5600000.0   44    PUNE
106             KEDAR    MALE   3900000.0   39   DELHI
107            MAHESH    MALE   1350000.0   43  MUMBAI
108             POOJA  FEMALE   4520000.0   32  NAGPUR
109            PRAPTI  FEMALE   4530000.0   39    PUNE
110          SHRUTIKA  FEMALE   7850000.0   42   DELHI
111            SIMRAN  FEMALE   5980000.0   34  MUMBAI
112          ASHUTOSH    MALE   9800000.0   36  NAGPUR
113             SURAJ    MALE   8130000.0   47    PUNE
114            SHWETA  FEMALE   7260000.0   47   DELHI
115            VEDIKA  FEMALE   6360000.0   44  MUMBAI
116            HARISH    MALE  45610000.0   42  NAGPUR
117             KEDAR    MALE   3900000.0   39    PUNE
118             POOJA  FEMALE   4520000.0   32   DELHI
119            ANKUSH    MALE         NaN   32  MUMBAI
120           KRISHNA    MALE         NaN   22  NAGPUR

In [177]:
df.groupby(by = ['CITY', 'GENDER'])['SALARY'].mean()

CITY    GENDER
DELHI   FEMALE    6.543333e+06
        MALE      2.700000e+06
MUMBAI  FEMALE    5.880000e+06
        MALE      1.350000e+06
NAGPUR  FEMALE    2.910000e+06
        MALE      2.770500e+07
PUNE    FEMALE    4.530000e+06
        MALE      4.432500e+06
Name: SALARY, dtype: float64